name: AlphaDental

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false  # Set CI to false
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build
      
    # - name: Deploy to Hostinger
    #   run: |
    #       rsync -avz --delete -e "ssh -p 65002 u499450812@89.117.27.252" build/ alphadentalgaya.com:/path/to/public_html/
    
    # - name: Push
           
    #   uses: s0/git-publish-subdir-action@develop
    #   with:
    #     github_token: ${{ secrets.PAT_TOKEN }}  # Use your personal access token
    #     publish_dir: ./build  # Your build directory
    #   env:
    #     REPO: self
    #     BRANCH: build # The branch name where you want to push the assets
    #     FOLDER: build # The directory where your assets are generated
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
    #     MESSAGE: "Build: ({sha}) {msg}" # The commit message

    - name: Push to Build Branch
      run: |
        git config user.name "ra2109"
        git config user.email "aftabroshan02@gmail.com"
        git reset --hard
        git fetch origin

        # Check if the build branch exists
        if git show-ref --verify --quiet refs/remotes/origin/build; then
          # If it exists, check it out
          git checkout -B build origin/build
        else
          # If it doesn't exist, create a new build branch
          git checkout -b build
        fi

        git rm -rf .
        cp -r build/* .
        git add .
        # Commit changes (if any)
        git commit -m "Deploy to build branch" || echo "No changes to commit"
        # Push changes
        git push --force https://${{ secrets.PAT_TOKEN }}@github.com/ra2109/Alpha-Dental.git build
      